### ISSUE TITLE
rmapi ddvk fork

### ISSUE THREAD

**Issue by ghost** [j6k4m8/remarkapy#14]
Just wanted to let you know that the [ddvk's fork](https://github.com/ddvk/rmapi) of rmapi still seems to work. Maybe it'll help this project.

**Comment by j6k4m8** [comment]
Very awesome — yes I've been tracking! I think it still merits a translation into Python to meet the needs of a lot of the projects that grew to depend on other libs, but I'm SO glad to see that the inimitable @ddvk is on the job! Hoping there will be some opportunities to synergize our efforts :) 

Thank you very much for the diligence, @KMIJPH! Would love to get your inputs if you encounter other projects that should serve as inspiration or that could be used by or useful to us!
